Refactor MatchService to use message queues and account for edge cases
CS3219-AY2223S1/cs3219-project-ay2223s1-g38 pull request #34
Opened 2022-10-06 12:51 UTC by tau-bar

Fixes #24, #17

Credit to @LZher385 for working on the timer on the frontend and creating the socket operations on `yuzher/match-ui` branch.

## Description
The edge cases have been accounted for. Verify using Postman by trying to match the same user with themselves/same socket with same socket, should not be able to find a match. On top of that, I have changed the structure of the MatchService to use RabbitMQ message queue.

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
The tests are the same as before, the tests are on our shared Postman collection. 

`match:find`
Send this event with { "user": 1, "difficulty": "MEDIUM" } for example.

`match:cancel`
Send this event to cancel the current matchmaking.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-09 17:51 UTC, LZher385 commented
Match find and match cancel events tested and working. However I noticed that there is no event emitted when a user is deleted from the queue once the 30 seconds timer is out. Do you think there is a need for this? I guess the we can just start the 30s timer on the frontend separately as well so that it doesn't have to wait for such an event

2022-10-13 16:48 UTC, tyanhan commented
![image](https://user-images.githubusercontent.com/68331979/195654881-1791439e-8fa9-4f42-8877-306c6f94afee.png)
Sending a match find request without difficulty causes the match service to be unable to start
![image](https://user-images.githubusercontent.com/68331979/195657034-b802ee57-24c2-4a8e-ae9b-c85548255402.png)

2022-10-14 14:43 UTC, tyanhan requested changes
LGTM, just some minor changes

2022-10-14 14:43 UTC, tyanhan commented on matching-service/consumer/repository/matchRepository.js
> +}
Missing `;` for the last function of most files

2022-10-14 14:43 UTC, tyanhan commented on matching-service/package.json
> +    "migrate": "./node_modules/.bin/sequelize db:migrate"
The migrate function doesn't seem to be working on my side. It says '.' is not a recognized command. I was wondering if it is related to this. https://stackoverflow.com/questions/66185466/npm-script-fails-is-not-recognized-as-an-internal-or-external-command

2022-10-16 10:00 UTC, tyanhan approved these changes
LGTM

2022-10-16 10:00 UTC, merged