Add collab service
CS3219-AY2223S1/cs3219-project-ay2223s1-g38 pull request #37
Opened 2022-10-13 15:30 UTC by tyanhan

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
![image](https://user-images.githubusercontent.com/68331979/195640027-3dfeb8b3-b7db-4001-98b7-1742759f0060.png)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-10-13 16:58 UTC, tau-bar commented
A few things to add:
1. Delete room endpoint (so that we can delete the room when the last person leaves)
2. Add endpoint to update the question id if user changes the question

2022-10-13 16:58 UTC, tau-bar requested changes

2022-10-13 16:58 UTC, tau-bar commented on collab-service/index.js
> +app.listen(PORT, () => console.log("question-service is listening on port ", PORT));
minor nit
```suggestion
app.listen(PORT, () => console.log("collab-service is listening on port ", PORT));
```

2022-10-13 17:51 UTC, tyanhan commented
Unique room ID not working on schema currently

2022-10-17 13:54 UTC, tau-bar approved these changes

2022-10-17 13:54 UTC, merged